CREATE OR REPLACE FUNCTION compiled()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
		BEGIN
		IF TG_OP = 'INSERT' THEN
		INSERT INTO questions VALUES(NEW.question);
		RETURN NEW;
		END IF;
		RETURN NEW;
	END;
$function$;
--CREATE TRIGGER compiled_trig
INSTEAD OF INSERT OR UPDATE OR DELETE ON 
compiled FOR EACH ROW EXECUTE PROCEDURE compiled();
INSERT INTO compiled VALUES(7);